delete_merged_branches = true
update_base_for_deletes = true

status = [
	"Test on macos with Rust stable (feat: default)",
	"Test on ubuntu with Rust stable (feat: default)",
	"Test on windows with Rust stable (feat: default)",
	"Test on macos with Rust 1.51.0 (feat: default)",
	"Test on ubuntu with Rust 1.51.0 (feat: default)",
	"Test on windows with Rust 1.51.0 (feat: default)",

	"Test on macos with Rust stable (feat: with-tokio)",
	"Test on ubuntu with Rust stable (feat: with-tokio)",
	"Test on windows with Rust stable (feat: with-tokio)",
	"Test on macos with Rust 1.51.0 (feat: with-tokio)",
	"Test on ubuntu with Rust 1.51.0 (feat: with-tokio)",
	"Test on windows with Rust 1.51.0 (feat: with-tokio)",
]

# Disabled until https://github.com/bors-ng/bors-ng/issues/1434 is fixed
#pr_status = [
#	"Clippy on macos (feat: default)",
#	"Clippy on ubuntu (feat: default)",
#	"Clippy on windows (feat: default)",
#
#	"Clippy on macos (feat: with-tokio)",
#	"Clippy on ubuntu (feat: with-tokio)",
#	"Clippy on windows (feat: with-tokio)",
#]
